"""Write tools/timing.json for the v2 cut from the real Sulafat phrase cues (tools/vo-cues.json).

Each scene starts LEAD seconds before the phrase that opens it; every scene receives every
phrase cue in its own local time, keyed "line.phrase" (e.g. "3.8" = line 3, phrase 8).
    python3 tools/plan.py && python3 tools/build.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CUES = json.loads((ROOT / "tools/vo-cues.json").read_text())
LEAD, GAP = 0.15, 0.6
BREATH_AFTER, EXHALE_IN, TAIL = 0.7, 1.75, 5.6

# absolute start of each take
line_start, t = {}, 0.4
for n in sorted(CUES, key=int):
    line_start[int(n)] = round(t, 3)
    t += CUES[n]["seconds"] + GAP
vo_end = line_start[5] + CUES["5"]["seconds"]
breath = round(vo_end + BREATH_AFTER, 3)
exhale = round(breath + EXHALE_IN, 3)
total = round(exhale + TAIL, 3)

cue = {}
for n, c in CUES.items():
    for i, p in enumerate(c["phrases"]):
        cue[f"{n}.{i}"] = round(line_start[int(n)] + p["start"], 3)
cue["breath"], cue["exhale"] = breath, exhale

# (scene id, phrase that opens it)
SCENES = [
    ("a1-rang", None), ("a2-croissance", "1.1"), ("a3-marque", "1.2"), ("a4-coherence", "1.5"),
    ("b1-ecouter", "2.0"), ("b2-deux-mondes", "2.2"), ("b3-reseau", "2.7"), ("b4-multiple", "2.10"), ("b5-isolee", "2.12"),
    ("c1-structure", "3.0"), ("c2-corps", "3.6"), ("c3-stature", "3.10"),
    ("d0-decliner", "4.0"), ("d1-supports", "4.2"), ("d2-site", "4.6"), ("d3-agent", "4.7"),
    ("e1-role", "5.0"), ("e2-organigramme", "5.4"), ("e3-autour", "5.6"), ("e4-cotes", "5.7"), ("e5-promesse", "5.12"),
    ("f-relax", "breath"),
]
starts = [0.0 if k is None else round(cue[k] - (0.3 if k == "breath" else LEAD), 3) for _, k in SCENES]
scenes = []
for i, (sid, _) in enumerate(SCENES):
    s = starts[i]
    e = starts[i + 1] if i + 1 < len(SCENES) else total
    scenes.append({"id": sid, "dur": round(e - s, 3), "vo": {k: round(v - s, 3) for k, v in cue.items()}})

audio = [{"id": "bgm", "src": "assets/audio/bed.wav", "start": 0, "volume": 1, "track": 2, "group": "music"},
         {"id": "breath", "src": "assets/audio/breath.wav", "start": breath, "volume": 1, "track": 3, "group": "sfx"},
         {"id": "whoosh", "src": "assets/audio/whoosh.wav", "start": 0, "volume": 1, "track": 4, "group": "sfx"}]
audio += [{"id": f"vo0{n}", "src": f"assets/voice/line-0{n}.wav", "start": line_start[n], "volume": 1, "track": 1,
           "group": "voiceover"} for n in sorted(line_start)]

out = {"_note": "Generated by tools/plan.py from tools/vo-cues.json (Sulafat takes). Do not edit by hand.",
       "total": total, "line_start": line_start, "cue": cue, "scenes": scenes, "audio": audio}
(ROOT / "tools/timing.json").write_text(json.dumps(out, ensure_ascii=False, indent=1) + "\n")
for sc, s in zip(scenes, starts):
    print(f"{sc['id']:14s} {s:7.2f}  {sc['dur']:5.2f}s")
print("total", total, "breath", breath, "exhale", exhale)
